### ISSUE TITLE
Make on RPI4

### ISSUE THREAD

**Issue by stg710** [SICKAG/sick_scan_base#1]
Hello,

I tried the given steps on a brand new RPI4 with Raspian.
I installed
 - Cmake
 - latest boost lib (1.7.0)

However, I got this message:

![image](https://user-images.githubusercontent.com/22135957/64095432-0e7a6400-cd5f-11e9-9724-9b01586ba1c0.png)

Is there anything I can do? 

BR

**Comment by michael1309** [comment]
Hi @stg710,

could you resolve this issue? 
Currently we only support Windows and Ubuntu 18.04LTS for x86 architectures with this software. If it only concerns date/time functions of boost, you could try to realize the time calculation with other C++ methods.

**Comment by stg710** [comment]
Hi michael1309,

many thanks for your support. I'll switch to x86 for further testing.

BR
