### ISSUE TITLE
It seems that the frequency of the scan demo too low.

### ISSUE THREAD

**Issue by jackieiou123** [SICKAG/sick_scan_base#17]
Hello, I  used a LMS511-20100 to test the demo, but it seems that the frequency of data updates is too low. 
I set the frequency of LMS511  at 25Hz, but the data updates in scan.csv need about 1 second.
Is there any way to set the data updates frequency?

**Comment by michael1309** [comment]
For performance reasons you cannot write a CSV file and a JPEG file for each scan. Therefore, this is only done for every 25th scan.

The logic can be found in the following line:    
https://github.com/SICKAG/sick_scan_base/blob/master/driver/src/sick_scan_common.cpp#L3767         
```
   if (cnt == 25)
```
In addition we recommend to use the repo. sick_scan_xd (see: https://github.com/SICKAG/sick_scan_xd )

**Comment by jackieiou123** [comment]
Thanks for your answer!
