### ISSUE TITLE
timestamp scan_reference

### ISSUE THREAD

**Issue by stg710** [SICKAG/sick_scan_base#2]
Hello,

I was wondering why the timestamp_sec and timestamp_nanosec does not update in the scan_refernce  .csv file? I tried with TiM571 and LMS4000. Do you have any clues?

//stg710

**Comment by michael1309** [comment]
Hi, 

we discussed this internally and will give you a feedback until end of this week.

**Comment by michael1309** [comment]
We fixed the time stamping issue and tested it with Ubuntu 18.04.
The timestamp could be checked by using https://www.epochconverter.com/ or similar.

**Comment by stg710** [comment]
Thank you for your help.
