### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by themightyoarfish** [SICKAG/sick_scan_base#3]
Is work on this still ongoing? Would love to have a driver for TiM or LMS family of scanners without having to use ROS.

**Comment by themightyoarfish** [comment]
Huh, I was confused by the presence of ROS calls throughout the code and assumed it was WIP conversion, but it actually compiles on 16.04 after setting the C++ version to 11.

**Comment by mikeNike9** [comment]
@themightyoarfish you do not have to use ROS wrapper if you dont want to. 

you can simply just extract all the code form the project you need to run your application.
Easier said then done but im a firm believer that if you stare at something long enough you will get it.
I believe SICK SCAN BASE will do this for you as well.

**Comment by themightyoarfish** [comment]
It looks like in order for this package to compile, it reimplements a lot of ROS stuff so it's portable without a full ROS installation.
The problem with the SICK ROS drivers has always been that they are not easy to disentangle from ROS, so that would be a big effort. This repo seems to be a step in that direction though.
