### ISSUE TITLE
LMS 1xx support

### ISSUE THREAD

**Issue by Thowaah** [SICKAG/sick_scan_base#5]
I did not see the LMS1xx in the list of supported devices. I would like to use this library to interface with this device. I saw that it is supported in the sick_scan library, but I don't want to use ROS. 

Would the LMS1xx work with this library, and if not, could some minor changes make it work ? 

Thanks for the help !

**Comment by rostest** [comment]
Issue is closed due to being inactive. Please feel free to reopen it in case it's still a topic.
