### ISSUE TITLE
Pthread issue Windows 10

### ISSUE THREAD

**Issue by owodunni** [SICKAG/sick_scan_base#6]
Hi,

I have been trying to get this compiling on Windows 10 without luck.

Here is what I did:

1.  Download boost 1.65.1
2.  Modify CMakeLists.txt to find boost.
```
set(Boost_INCLUDE_DIRS "C:/local/boost_1_65_1")
set(Boost_DIR "C:/local/boost_1_65_1")
set(Boost_LIBRARY_DIR "C:/local/boost_1_65_1/lib64-msvc-14.1")
```
target_link_libraries(sick_generic_caller libboost_system-vc141-mt-s-1_65_1.lib   libboost_thread-vc141-mt-s-1_65_1.lib  libboost_filesystem-vc141-mt-s-1_65_1.lib)

1.  mkdir build && cd build
2.  cmake .. -A x64
3.  Open visual studio and compile
```
2>C:\Projects\sick_scan_base-master\roswrap\src\cfgsimu\sick_scan\time_modi.cpp(466): error C3861: 'usleep': identifier not found2>rossimu.cpp2>Unknown compiler version - please run the configure tests and report the results2>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:2>- add -D_WIN32_WINNT=0x0501 to the compiler command line; or2>- add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.2>Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).2>C:\Projects\sick_scan_base-master\include\sick_scan/tcp/SickThread.hpp(9): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory2>duration.cpp2>Unknown compiler version - please run the configure tests and report the results
```

After sniffing around in the code I cannot find any ifdefs regarding pthread. So I have no idea how this is supposed to work on Windows. I guess there is [https://sourceware.org/pthreads-win32/](https://sourceware.org/pthreads-win32/) and [https://docs.microsoft.com/en-us/previous-versions/tn-archive/bb463209(v=technet.10)?redirectedfrom=MSDN](https://docs.microsoft.com/en-us/previous-versions/tn-archive/bb463209(v=technet.10)?redirectedfrom=MSDN) But before I try those options I would like to know if they are required or if I am missing something.

Best Regards
Alexander Poole

**Comment by michael1309** [comment]
Hi 

we will check it and give you a feedback tomorrow.

Best regards

**Comment by michael1309** [comment]
Hi,

after investigating this issue I recommend to use vcpkg for build the solution in a more reliable way.

Here are my recommendations:
1. setup vcpkg
see   `https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=msvc-160` for details
2. install boost using vcpkg
```vcpkg install boost:x86-windows``` (needs round about 30 min.)
3. install pthread 
```vcpkg install pthread:x86-windows```
4. Modify first line of `build.bat`
```
set vcpkg=-DCMAKE_TOOLCHAIN_FILE=%USERPROFILE%/documents/development/vcpkg/scripts/buildsystems/vcpkg.cmake
```
to point to your local copy of vcpkg.cmake
4. run 
```build.bat```
5. Open `sick_scan_base.sln` in the `build`-directory.

**Comment by owodunni** [comment]
Hi Michael,

Thank you very much with your instructions we managed to get it building for x64.

However I have some further questions we aim to consume your library as a dll instead of an exe. Getting it building was trivial enough but now comes the tricky part.

Do you have a quick guide of what parts of the code we should look at regarding what functions we need to export out of the .dll in order to get this working? Or any other suggestions in regards of using this as a library instead of a standalone program?

**Comment by michael1309** [comment]
You can of course build a DLL where you define some important functions.
E.g. init, close, etc.
Then you can register a callback function. You call this callback function every time a scan comes in.
The best place to do this is at the point where a publish of the pointcloud is done. Here you can also call a callback function in a DLL. The whole main program then runs in a separate thread. Please understand that I am closing this ticket now, as this is a separate topic that is outside of sick_scan.
